### ISSUE TITLE
undefined is not an object 

### ISSUE THREAD

**Issue by ammichael** [caroaguilar/react-native-bar-collapsible#2]
Hi there!

I'm trying to use your component but its giving me this error: 
![error](https://cloud.githubusercontent.com/assets/6873880/21246054/6bee7ee6-c30d-11e6-8cd1-4cbb9a131167.png)

I have react-native-vector-icons installed, and I'm already using it in the app. Also, I've restarted the packager. 

Any idea?

Thanks!

**Comment by caroaguilar** [comment]
Hi, the issue seems to be completely related to the react-native-vector package. Already opened a ticket with them, as soon as I get a response I'll fix this component.

Thanks!
