### ISSUE TITLE
How to make some bars opened

### ISSUE THREAD

**Issue by rizki82** [caroaguilar/react-native-bar-collapsible#6]
I have two bars, but i want the first bar is opened by default, how can i do this?

**Comment by caroaguilar** [comment]
Hi,

That feature was added in the latest pull request https://github.com/caroaguilar/react-native-bar-collapsible/pull/5

You just need to pass a `showOnStart={true}` property to the bar you want to be opened by default.

I hadn't update the README sorry about that. Already did it https://github.com/caroaguilar/react-native-bar-collapsible#collapsible .
