### ISSUE TITLE
Issue on title and icon.

### ISSUE THREAD

**Issue by Praveen-Bips** [caroaguilar/react-native-bar-collapsible#7]
Why cant the icons doesnt have any props to style it. And one more issue i have.
I used the bar inside the Image Tag, the width of title goes beyond the screen width, so that the icon disappers in the right side in android mobile. Please give some suggestions to solve it.

**Comment by glebcha** [comment]
@Praveen-Bips @caroaguilar added icon style in https://github.com/caroaguilar/react-native-bar-collapsible/pull/10

**Comment by caroaguilar** [comment]
Fixed in #10
New version of the component is already pushed to NPM.

Thanks
