### ISSUE TITLE
undefined is not an object (evaluating '_reactNative.PropTypes.string')

### ISSUE THREAD

**Issue by Yoruba** [caroaguilar/react-native-bar-collapsible#8]
Please change 

`import React, { PropTypes, Component } from 'react';`

With

```
import React, { Component } from 'react';
import PropTypes from 'prop-types'
```
To support react 15.5 or higher.

Thanks, Adri

**Comment by caroaguilar** [comment]
Fixed in https://github.com/caroaguilar/react-native-bar-collapsible/pull/10
New version of the component is already pushed to NPM.

Thanks
